name: Build MeshAgent EXE

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build MeshAgent
      shell: pwsh
      run: ./compileall

    - name: Upload meshagent.exe
      uses: actions/upload-artifact@v4
      with:
        name: meshagent-exe
        path: meshagent.exe
